# Generated by Django 5.0.6 on 2024-05-20 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_remove_position_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="updated",
        ),
    ]
